### ISSUE TITLE
Library fails to compile on framework-arduinoespressif32 @ 3.0.0

### ISSUE THREAD

**Issue by PureTek-Innovations** [tobiasschuerg/InfluxDB-Client-for-Arduino#226]
I have some hardware in my project that I can only get working with Arduino V3.0.0, so I am using this alpha version.

__Steps to reproduce:__

1. add "tobiasschuerg/ESP8266 Influxdb @ ^3.13.1" to lib-deps section of platformio.ini
2. Try to compile

__Expected behavior:__
Compile the project

__Actual behavior:__
I get this error:
`Compiling .pio\build\esp32-s3-devkitc-1\libd2f\ESP8266 Influxdb\Point.cpp.o 
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp: In constructor 'HTTPService::HTTPService(ConnectionInfo*)':
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp:37:5: error: 'WiFiClientSecure' was not declared in this scope; did you mean 'WiFiClientRxBuffer'?
   37 |     WiFiClientSecure *wifiClientSec = new WiFiClientSecure;
      |     ^~~~~~~~~~~~~~~~
      |     WiFiClientRxBuffer
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp:37:23: error: 'wifiClientSec' was not declared in this scope; did you mean '_wifiClient'?
   37 |     WiFiClientSecure *wifiClientSec = new WiFiClientSecure;
      |                       ^~~~~~~~~~~~~
      |                       _wifiClient
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp:37:43: error: 'WiFiClientSecure' does not name a type; did you mean 'WiFiClientRxBuffer'?
   37 |     WiFiClientSecure *wifiClientSec = new WiFiClientSecure;
      |                                           ^~~~~~~~~~~~~~~~
      |                                           WiFiClientRxBuffer
*** [.pio\build\esp32-s3-devkitc-1\libd2f\ESP8266 Influxdb\HTTPService.cpp.o] Error 1`

__Specifications:__
 - Library Version: 3.13.1
 - InfluxDB Version: n/a
 - Board/ESP chip: ESP32-S3
 - Device Arduino SDK version: 3.0.0

**Comment by PureTek-Innovations** [comment]
I just tried the library V3.13.0 in the arduino IDE version 1.8.19 with ESP32 Core version 3.0.0.0 alpha3 and it compiles!
It looks like this issue is elsewhere.
I'll see if I can force platformio to use version 3.13.0

**Comment by rodri16** [comment]
Same error using :

- Library Version: 3.13.1
- Board/ESP chip: ESP32-S3
- [Arduino Release v3.0.0 RC1 based on ESP-IDF v5.1](https://github.com/espressif/arduino-esp32/releases/tag/3.0.0-rc1)
- Library Version: 3.13.1

**Comment by chinswain** [comment]
Same error using the stable version:

Library Version: 3.13.1
Board/ESP chip: ESP32-S3
[Arduino Release v3.0.0  based on ESP-IDF v5.1.4](https://github.com/espressif/arduino-esp32/releases/tag/3.0.0-rc1)

Library migration guide: https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html
