### ISSUE TITLE
3.11.0 - ESP32 undefined reference to `Point::Point(String const&)'

### ISSUE THREAD

**Issue by szerwi** [tobiasschuerg/InfluxDB-Client-for-Arduino#184]
Hi,

I get following error during compilation: ```undefined reference to `Point::Point(String const&)'```

Here is how creating Point object looks in my code:
```
#define MEASUREMENT_NAME "ESP32"
...
Point dbData(MEASUREMENT_NAME);
```
Exactly the same code works fine on 3.10.0. I think there is some bug in 3.11.0 changes.

__Specifications:__
 - Library Version: 3.11.0
 - InfluxDB Version: -
 - Board/ESP chip: ESP32 Dev Module
 - Device Arduino SDK version: arduino-esp32 2.0.2

**Comment by vlastahajek** [comment]
Such is code is used by everyone who uses this library.
Of course, this is successfully compiled under Arduino IDE. Even using PlatformIO with the latest official framework `espressif32`.
There must be a problem with your toolchain. Try clean build.

**Comment by szerwi** [comment]
It works after clean build, thanks.
I haven't thought it may be a caching issue.
