### PR TITLE
fix: ESP32 Core 3 compatibility

### LINKED ISSUE #226: Library fails to compile on framework-arduinoespressif32 @ 3.0.0
I have some hardware in my project that I can only get working with Arduino V3.0.0, so I am using this alpha version.

__Steps to reproduce:__

1. add "tobiasschuerg/ESP8266 Influxdb @ ^3.13.1" to lib-deps section of platformio.ini
2. Try to compile

__Expected behavior:__
Compile the project

__Actual behavior:__
I get this error:
`Compiling .pio\build\esp32-s3-devkitc-1\libd2f\ESP8266 Influxdb\Point.cpp.o 
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp: In constructor 'HTTPService::HTTPService(ConnectionInfo*)':
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp:37:5: error: 'WiFiClientSecure' was not declared in this scope; did you mean 'WiFiClientRxBuffer'?
   37 |     WiFiClientSecure *wifiClientSec = new WiFiClientSecure;
      |     ^~~~~~~~~~~~~~~~
      |     WiFiClientRxBuffer
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp:37:23: error: 'wifiClientSec' was not declared in this scope; did you mean '_wifiClient'?
   37 |     WiFiClientSecure *wifiClientSec = new WiFiClientSecure;
      |                       ^~~~~~~~~~~~~
      |                       _wifiClient
.pio/libdeps/esp32-s3-devkitc-1/ESP8266 Influxdb/src/HTTPService.cpp:37:43: error: 'WiFiClientSecure' does not name a type; did you mean 'WiFiClientRxBuffer'?
   37 |     WiFiClientSecure *wifiClientSec = new WiFiClientSecure;
      |                                           ^~~~~~~~~~~~~~~~
      |                                           WiFiClientRxBuffer
*** [.pio\build\esp32-s3-devkitc-1\libd2f\ESP8266 Influxdb\HTTPService.cpp.o] Error 1`

__Specifications:__
 - Library Version: 3.13.1
 - InfluxDB Version: n/a
 - Board/ESP chip: ESP32-S3
 - Device Arduino SDK version: 3.0.0

### PR DESCRIPTION
**Pull request by vlastahajek**
Closes #226 

## Proposed Changes

Added explicit includes which were part of `HTTPClient.h` in ESP32 core 2.x.x

## Checklist

- [x] CHANGELOG.md updated
- [X] Rebased/mergeable
- [ ] A test has been added if appropriate
- [X] Tests pass
- [X] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)

### CODE REVIEW

**Comment by jezmck** [comment]
Phew, I thought I was going insane! 
I was already adding the removed libs for my own code, so was very confused by the error messages.

Thanks for the fix.
